#! /bin/sh

#------------------------------------------------------------------------------#
#                                   start up                                   #
#------------------------------------------------------------------------------#
source ~/workspace/dothome/init/env.sh
source ~/workspace/dothome/init/startup.sh

sxhkd &

st &
st &
st &
chromium &


#------------------------------------------------------------------------------#
#                               monitor settings                               #
#------------------------------------------------------------------------------#
bspc monitor -d I II III IV V VI VII VIII IX X


#------------------------------------------------------------------------------#
#                                    themes                                    #
#------------------------------------------------------------------------------#
bspc config border_width         				2
bspc config window_gap           				20
bspc config split_ratio          				0.50
bspc config borderless_monocle   				true
bspc config gapless_monocle						true
bspc config normal_border_color  				"#1D1F21"
bspc config active_border_color  				"#A54242"
bspc config focused_border_color				"#ff3d3d"
bspc config presel_feedback_color				"#F0C674"


#------------------------------------------------------------------------------#
#                               application rules                              #
#------------------------------------------------------------------------------#
bspc rule -a csgo_linux64 	desktop='^1'
bspc rule -a Darktable 		desktop='^1' 			state=fullscreen
bspc rule -a Gimp	 		desktop='^1' 			state=fullscreen
bspc rule -a kdenlive	 	desktop='^1' 			state=fullscreen
bspc rule -a code-oss		desktop='^1' 			state=floating
bspc rule -a "Tor Browser" 	desktop='^2' 			state=floating
bspc rule -a Steam 			desktop='^2' 			state=floating
bspc rule -a Chromium		desktop='^3'
bspc rule -a firefox		desktop='^3'
bspc rule -a Thunar 		desktop='^4' 			state=fullscreen
bspc rule -a dolphin 		desktop='^4' 			state=fullscreen
bspc rule -a Screenkey		manage=off
